# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.12.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [16]:
tensor3 = tensor_1 + tensor_2
with tf.Session() as sess:
    print(sess.run(tensor3))

3


In [17]:
sess

In [18]:
sess.close()

## Operations

In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4),10)

In [21]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [24]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [25]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [26]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [27]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.21325244  1.43399    -0.5930852   0.20479314]
 [ 0.25551462 -0.34766212  0.8939697   0.6930943 ]
 [ 0.34390685  0.1851363  -0.4705633  -0.05683371]
 [ 0.65755486  0.71448374 -0.30375093 -0.04662225]]


[[0.79705596 0.22548378 0.00462878 0.24027002]
 [0.6492324  0.35355878 0.19963872 0.96919906]
 [0.3461647  0.44663072 0.24085331 0.97943795]
 [0.8697684  0.8691319  0.850086   0.5564842 ]]




## Matrix Multiplication

In [28]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [29]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [30]:
b = tf.constant([[10],[100]])

In [31]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [32]:
result = tf.matmul(a,b)

In [33]:
result

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=int32>

In [34]:
result.eval()

array([[210],
       [430]])